name: Update Papers and Generate Web View

on:
  # label:
  #   types:
  #     - created # for test
  schedule:
    - cron: '30 16 * * *' # 00:30 Singapore time every day
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: List files
      run: |
        ls -l

    - name: Install dependencies
      run: |
        pip3 install -r ./requirements.txt

    - name: Update papers
      run: |
        python3 main.py
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: '✏️ Update papers (${{ steps.date.outputs.date }})'
        files: 'README.md papers/**/*'
        name: XinLi
        email: lixin.1997.lixin@gmail.com